# 📁 Configurações Iniciais

##📦 Instalação e Importações

In [ ]:
# Instala pacotes necessários
%pip install sidrapy
%pip install openpyxl
%pip install odfpy
# Importações essenciais
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from IPython.display import display
import sidrapy
from sidrapy import get_table
import sklearn
import os
import time
from google.colab import drive

# Montar o Google Drive
drive.mount('/content/drive')

Collecting sidrapy
  Downloading sidrapy-0.1.4-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from sidrapy) (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from sidrapy) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->sidrapy) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->sidrapy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->sidrapy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->sidrapy) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->sidrapy) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->sidrapy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->sidrapy) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->sidrapy) (2025.4.26)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->sidrapy) (1.17.0)
Downloading sidrapy-0.1.4-py3-none-any.whl (6.9 kB)
Installing collected packages: sidrapy
Successfully installed sidrapy-0.1.4
Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl) (2.0.0)
Collecting odfpy
  Downloading odfpy-1.4.1.tar.gz (717 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 717.0/717.0 kB 10.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: defusedxml in /usr/local/lib/python3.11/dist-packages (from odfpy) (0.7.1)
Building wheels for collected packages: odfpy
  Building wheel for odfpy (setup.py) ... done
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=160673 sha256=117e210697b329191ab49d2c104ffa2fb5fe0849255146591e706007bfca7914
  Stored in directory: /root/.cache/pip/wheels/d6/1d/c8/8c29be1d73ca42d15977c75193d9f39a98499413c2838ac54c
Successfully built odfpy
Installing collected packages: odfpy
Successfully installed odfpy-1.4.1
Mounted at /content/drive

# 📂 Leitura dos Arquivos

##LOAD & TRANSFORM - SIDRA | TABELA 5457 (2022)

In [ ]:
#Load na base de 2022
caminho_arquivo = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/RAW/2022/(2022) SIDRA Top10 - 5457.xlsx'

In [ ]:
# Carregar todas as abas
abas = pd.ExcelFile(caminho_arquivo)

# Ler a aba "Área plantada (Hectares)"
df_area_plantada = abas.parse("Área plantada (Hectares)")

# Verificar os tipos de dados por coluna
print(df_area_plantada.dtypes)

Nível                                                                                               object
Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica    object
Total                                                                                               object
Algodão herbáceo (em caroço)                                                                        object
Arroz (em casca)                                                                                    object
Cacau (em amêndoa)                                                                                  object
Café (em grão) Total                                                                                object
Cana-de-açúcar                                                                                      object
Feijão (em grão)                                                                                    object
Fumo (em folha)                                                                                     object
Laranja                                                                                             object
Milho (em grão)                                                                                     object
Soja (em grão)                                                                                      object
dtype: object

In [ ]:
# Carregar a primeira aba do arquivo
df = pd.read_excel(caminho_arquivo, sheet_name=0)

# Corrigir tipo da coluna categórica
df['Nível'] = df['Nível'].astype('category')

# Listar as colunas numéricas
colunas_numericas = [
    'Total',
    'Algodão herbáceo (em caroço)',
    'Arroz (em casca)',
    'Cacau (em amêndoa)',
    'Café (em grão) Total',
    'Cana-de-açúcar',
    'Feijão (em grão)',
    'Fumo (em folha)',
    'Laranja',
    'Milho (em grão)',
    'Soja (em grão)'
]

# Converter colunas numéricas com segurança
df[colunas_numericas] = df[colunas_numericas].apply(pd.to_numeric, errors='coerce')

# Adicionar coluna de ano (série temporal)
df['Ano'] = 2022

# Verificar tipos finais
print(df.dtypes)

KeyboardInterrupt:

In [ ]:
# Visualizar as 10 primeiras linhas
df.head(10)

,Nível,"Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica",Total,Algodão herbáceo (em caroço),Arroz (em casca),Cacau (em amêndoa),Café (em grão) Total,Cana-de-açúcar,Feijão (em grão),Fumo (em folha),Laranja,Milho (em grão),Soja (em grão),Ano
0,GR,Norte,5550519.0,15535.0,208353.0,161704.0,59044.0,53624.0,98945.0,152.0,19407.0,1211328.0,2617967.0,2022
1,GR,Nordeste,11916290.0,348902.0,160807.0,424745.0,118777.0,925905.0,1313314.0,21450.0,94688.0,2934118.0,3753375.0,2022
2,GR,Sudeste,16053282.0,36034.0,14681.0,15627.0,1641783.0,6592568.0,386869.0,408.0,403419.0,2165005.0,3275074.0,2022
3,GR,Sul,23786770.0,48.0,1129388.0,NaN,30773.0,538086.0,605445.0,306878.0,43910.0,4194084.0,12825384.0,2022
4,GR,Centro-Oeste,33994538.0,1249105.0,143179.0,724.0,19190.0,1794130.0,328937.0,120.0,9024.0,10805714.0,18825863.0,2022
5,UF,Rondônia,961956.0,10050.0,40221.0,7563.0,57475.0,502.0,3137.0,NaN,373.0,322237.0,489526.0,2022
6,UF,Acre,92287.0,NaN,3705.0,NaN,1062.0,480.0,5235.0,142.0,493.0,40460.0,6570.0,2022
7,UF,Amazonas,120030.0,NaN,1065.0,1214.0,320.0,4775.0,989.0,NaN,1237.0,2554.0,5900.0,2022
8,UF,Roraima,150608.0,NaN,10710.0,90.0,NaN,190.0,965.0,NaN,1435.0,15720.0,102785.0,2022
9,UF,Pará,2313220.0,NaN,40556.0,152837.0,187.0,17479.0,27360.0,10.0,15197.0,405590.0,839560.0,2022

In [ ]:
# 📄 Listar as abas do Excel
abas = pd.ExcelFile(caminho_arquivo).sheet_names

# 🏷️ Colunas categóricas e numéricas
coluna_categoria = 'Nível'
colunas_numericas = [
    'Total',
    'Algodão herbáceo (em caroço)',
    'Arroz (em casca)',
    'Cacau (em amêndoa)',
    'Café (em grão) Total',
    'Cana-de-açúcar',
    'Feijão (em grão)',
    'Fumo (em folha)',
    'Laranja',
    'Milho (em grão)',
    'Soja (em grão)'
]

# 📦 Dicionário para armazenar os DataFrames
dfs = {}

# 🔁 Loop pelas abas do Excel
for nome_aba in abas:
    # Nome do DataFrame com ano
    nome_df = f"df_2022_{nome_aba.lower().replace(' ', '_').replace('-', '_').replace('(', '').replace(')', '')}"

    # 📥 Ler aba
    df_temp = pd.read_excel(caminho_arquivo, sheet_name=nome_aba)

    # 🏷️ Tipagem da coluna categórica
    if coluna_categoria in df_temp.columns:
        df_temp[coluna_categoria] = df_temp[coluna_categoria].astype('category')

    # 🔢 Tipagem de colunas numéricas
    for col in colunas_numericas:
        if col in df_temp.columns:
            df_temp[col] = pd.to_numeric(df_temp[col], errors='coerce')

    # 📆 Adicionar coluna de ano
    df_temp['Ano'] = 2022

    # 💾 Salvar no dicionário
    dfs[nome_df] = df_temp

# 🧹 Limpeza e Padronização dos Dados

In [ ]:
dfs.keys()

dict_keys(['df_2022_área_plantada_hectares', 'df_2022_área_percentual_do_total_geral', 'df_2022_área_colhida_hectares', 'df_2022_área_colhida___percentual_total', 'df_2022_qtd_produzida___toneladas', 'df_2022_rendimento_médio_kg_x_hectare', 'df_2022_valor_da_produção_mil_reais', 'df_2022_valor_da_produção___%_do_total_'])

In [ ]:
# 📦 Dicionário final para armazenar os DataFrames por aba e nível
dfs_nivel = {}

# 🔁 Iterar sobre os DataFrames já carregados e tipados
for nome_df, df in dfs.items():

    # ✅ Garantir que a coluna 'Nível' exista e seja categórica
    if 'Nível' in df.columns:
        df['Nível'] = df['Nível'].astype('category')

        # 🕒 Extrair o ano a partir do nome do DataFrame
        if "2022" in nome_df:
            ano = 2022
        elif "2023" in nome_df:
            ano = 2023
        else:
            ano = None  # fallback para debugging se necessário

        # 🏷️ Adicionar coluna 'Ano' ao DataFrame
        df['Ano'] = ano

        # 🔢 Colunas numéricas a serem convertidas
        colunas_numericas = [
            'Total',
            'Algodão herbáceo (em caroço)',
            'Arroz (em casca)',
            'Cacau (em amêndoa)',
            'Café (em grão) Total',
            'Cana-de-açúcar',
            'Feijão (em grão)',
            'Fumo (em folha)',
            'Laranja',
            'Milho (em grão)',
            'Soja (em grão)'
        ]

        for col in colunas_numericas:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')

        # 🔍 Separar e salvar por cada nível único encontrado
        for nivel in df['Nível'].dropna().unique():
            nivel_nome = str(nivel).strip().lower().replace(" ", "_")
            nome_final = f"{nome_df}_{nivel_nome}"

            # Criar cópia do DataFrame filtrado
            df_nivel = df[df['Nível'] == nivel].copy()

            # Armazenar no dicionário
            dfs_nivel[nome_final] = df_nivel

# ✅ Visualizar os primeiros nomes gerados
for nome in list(dfs_nivel.keys())[:10]:
    print(nome)

df_2022_área_plantada_hectares_gr
df_2022_área_plantada_hectares_uf
df_2022_área_plantada_hectares_mu
df_2022_área_plantada_hectares_me
df_2022_área_plantada_hectares_mi
df_2022_área_plantada_hectares_fonte:_ibge_-_produção_agrícola_municipal
df_2022_área_percentual_do_total_geral_gr
df_2022_área_percentual_do_total_geral_uf
df_2022_área_percentual_do_total_geral_mu
df_2022_área_percentual_do_total_geral_me

In [ ]:
# Caminho da pasta já existente
caminho_destino = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/2022/'

# Salvar cada DataFrame do dicionário dfs_nivel
for nome, df in dfs_nivel.items():
    df.to_excel(f"{caminho_destino}{nome}.xlsx", index=False)

##LOAD & TRANSFORM - SIDRA | TABELA 5457 (2023)

In [ ]:
import pandas as pd
import os

# Caminhos
caminho_arquivo_2023 = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/RAW/2023/(2023) -  SIDRA Top10 - 5457.xlsx'
caminho_saida = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/2023'

# Parâmetros
coluna_categoria = 'Nível'
colunas_numericas = [
    'Algodão herbáceo (em caroço)',
    'Arroz (em casca)',
    'Cacau (em amêndoa)',
    'Café (em grão) Total',
    'Cana-de-açúcar',
    'Feijão (em grão)',
    'Fumo (em folha)',
    'Laranja',
    'Milho (em grão)',
    'Soja (em grão)'
]
ano_referencia = 2023

# Listar abas
abas_2023 = pd.ExcelFile(caminho_arquivo_2023).sheet_names
dfs_2023 = {}

# Carregar e tratar cada aba
for nome_aba in abas_2023:
    nome_base = nome_aba.lower().replace(" ", "_").replace("-", "_").replace("(", "").replace(")", "")
    nome_df = f"df_2023_{nome_base}"
    df_temp = pd.read_excel(caminho_arquivo_2023, sheet_name=nome_aba)

    # Tipagem
    if coluna_categoria in df_temp.columns:
        df_temp[coluna_categoria] = df_temp[coluna_categoria].astype('category')

    for col in colunas_numericas:
        if col in df_temp.columns:
            df_temp[col] = pd.to_numeric(df_temp[col], errors='coerce')

    # Criar coluna Total
    colunas_validas = [col for col in colunas_numericas if col in df_temp.columns]
    df_temp['Total'] = df_temp[colunas_validas].sum(axis=1)

    # Criar coluna Ano
    df_temp['Ano'] = ano_referencia

    # Reorganizar colunas: Nível, Local, Total, Métricas..., Ano
    colunas = list(df_temp.columns)
    geo_col = colunas[1]
    nova_ordem = [coluna_categoria, geo_col, 'Total'] + [c for c in colunas if c not in [coluna_categoria, geo_col, 'Total', 'Ano']] + ['Ano']
    df_temp = df_temp[nova_ordem]

    dfs_2023[nome_df] = df_temp

# Separar por nível e exportar
for nome_df, df in dfs_2023.items():
    if 'Nível' in df.columns:
        for nivel in df['Nível'].dropna().unique():
            nivel_nome = str(nivel).strip().lower().replace(" ", "_")
            nome_final = f"{nome_df}_{nivel_nome}"

            df_nivel = df[df['Nível'] == nivel].copy()

            # Garantir ordenação correta
            colunas = list(df_nivel.columns)
            if 'Total' in colunas:
                colunas.remove('Total')
                colunas.insert(2, 'Total')
            if 'Ano' in colunas:
                colunas.remove('Ano')
                colunas.append('Ano')
            df_nivel = df_nivel[colunas]

            # Exportar
            caminho_saida_final = os.path.join(caminho_saida, f"{nome_final}.xlsx")
            df_nivel.to_excel(caminho_saida_final, index=False)

In [ ]:
# 📦 Importando bibliotecas
import pandas as pd
import numpy as np

# 📁 Caminhos dos arquivos
dim_geo_path = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Dimensão/dim_geografica_expandida.xlsx'
fato_absoluto_path = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Fato/fato_absoluto_expandido_corrigido.xlsx'
fato_percentual_path = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Fato/fato_percentual_expandido_corrigido.xlsx'
dim_ano_path = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Dimensão/dim_ano.xlsx'
output_path = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Refatoradas/'

# 📄 Leitura dos dados
dim_geo = pd.read_excel(dim_geo_path)
fato_abs = pd.read_excel(fato_absoluto_path)
fato_perc = pd.read_excel(fato_percentual_path)
dim_ano = pd.read_excel(dim_ano_path)

# ✅ Padronização dos nomes de coluna
dim_geo.columns = dim_geo.columns.str.strip().str.lower()
dim_ano.columns = dim_ano.columns.str.strip().str.lower()

# 🧱 Tabelas geográficas a partir do 'nível'
def criar_tabela_localizacao(df, nivel_valor, nome_coluna):
    return pd.DataFrame({
        nome_coluna: df[df['nível'] == nivel_valor]['localização'].dropna().drop_duplicates().reset_index(drop=True)
    })

dim_grande_regiao = criar_tabela_localizacao(dim_geo, 'GR', 'grande_regiao')
dim_uf = criar_tabela_localizacao(dim_geo, 'UF', 'uf')
dim_municipio = criar_tabela_localizacao(dim_geo, 'MU', 'municipio')
dim_mesorregiao = criar_tabela_localizacao(dim_geo, 'ME', 'mesorregiao')
dim_microrregiao = criar_tabela_localizacao(dim_geo, 'MI', 'microrregiao')

# 🧱 Dimensão Nível Geográfico
dim_nivel = pd.DataFrame({'nivel': dim_geo['nível'].dropna().unique()})

# 📍 Dimensão Código UF
dim_codigo_uf = pd.DataFrame({'codigo_uf': dim_geo['código uf'].dropna().unique()})

# 🧾 Dimensão Produto
produtos = [
    "Algodão herbáceo (em caroço)", "Arroz (em casca)", "Cacau (em amêndoa)", "Café (em grão) Total",
    "Cana-de-açúcar", "Feijão (em grão)", "Fumo (em folha)", "Laranja", "Milho (em grão)", "Soja (em grão)"
]
dim_produtos = pd.DataFrame({'produto': produtos})

# 📅 Dimensão Ano
dim_ano['ano'] = pd.to_datetime(dim_ano['ano'], format='%Y')
dim_ano.drop_duplicates(inplace=True)

# ⚖️ Dimensão Medidas
def classificar_medida(col):
    col = col.lower()
    if 'tonelada' in col or 'kg' in col:
        return 'toneladas'
    elif 'hectare' in col:
        return 'hectares'
    elif 'valor' in col or 'r$' in col:
        return 'reais'
    elif '%' in col or 'percentual' in col:
        return 'percentual'
    else:
        return 'outro'

def descricao_medida(tipo):
    return {
        'toneladas': 'Peso (tonelada = 1000kg)',
        'hectares': 'Área cultivada (ha)',
        'reais': 'Valor monetário (R$)',
        'percentual': 'Indicador percentual (%)',
        'outro': 'Outra métrica'
    }[tipo]

medidas_numericas = list(set(
    [col for col in fato_abs.columns if fato_abs[col].dtype in ['float64', 'int64']] +
    [col for col in fato_perc.columns if fato_perc[col].dtype in ['float64', 'int64']]
))

dim_medidas = pd.DataFrame({'medida': medidas_numericas})
dim_medidas['tipo'] = dim_medidas['medida'].apply(classificar_medida)
dim_medidas['descricao'] = dim_medidas['tipo'].apply(descricao_medida)
dim_medidas.drop_duplicates(inplace=True)

# 💾 Exportação de todas as dimensões
dim_nivel.to_excel(output_path + "dim_nivel.xlsx", index=False)
dim_codigo_uf.to_excel(output_path + "dim_codigo_uf.xlsx", index=False)
dim_grande_regiao.to_excel(output_path + "dim_grande_regiao_corrigido.xlsx", index=False)
dim_uf.to_excel(output_path + "dim_uf.xlsx", index=False)
dim_municipio.to_excel(output_path + "dim_municipio.xlsx", index=False)
dim_mesorregiao.to_excel(output_path + "dim_mesorregiao.xlsx", index=False)
dim_microrregiao.to_excel(output_path + "dim_microrregiao.xlsx", index=False)
dim_produtos.to_excel(output_path + "dim_produtos.xlsx", index=False)
dim_ano.to_excel(output_path + "dim_ano_formatado.xlsx", index=False)
dim_medidas.to_excel(output_path + "dim_medidas.xlsx", index=False)

print("✅ Todas as dimensões foram geradas e exportadas com sucesso.")

✅ Todas as dimensões foram geradas e exportadas com sucesso.

In [ ]:
# Carregamento das tabelas fato
fato_abs = pd.read_excel('/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Fato/fato_absoluto_expandido_corrigido.xlsx')
fato_pct = pd.read_excel('/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Fato/fato_percentual_expandido_corrigido.xlsx')

# Exibir as primeiras linhas
print("Fato Absoluto")
display(fato_abs.head())

print("Fato Percentual")
display(fato_pct.head())

Fato Absoluto

,Nível,Código UF,"Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica",Total,Algodão herbáceo (em caroço),Arroz (em casca),Cacau (em amêndoa),Café (em grão) Total,Cana-de-açúcar,Feijão (em grão),Fumo (em folha),Laranja,Milho (em grão),Soja (em grão),Ano,Tipo de Dado,Arquivo Origem
0,MU,SP,Igaratá (SP),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mu.xlsx
1,MU,SP,Igaratá (SP),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_plantada_hectares_mu.xlsx
2,MI,SP,Osasco (SP),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mi.xlsx
3,MI,SP,Santos (SP),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mi.xlsx
4,MU,MG,Contagem (MG),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mu.xlsx

Fato Percentual

,Nível,Código UF,"Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica",Total,Algodão herbáceo (em caroço),Arroz (em casca),Cacau (em amêndoa),Café (em grão) Total,Cana-de-açúcar,Feijão (em grão),Fumo (em folha),Laranja,Milho (em grão),Soja (em grão),Ano,Tipo de Dado,Arquivo Origem
0,ME,CE,Noroeste Cearense (CE),100.0,0.0,0.18,NaN,0.12,3.06,5.54,NaN,0.28,4.97,0.58,2022,Percentual,df_2022_valor_da_produção_____do_total__me.xlsx
1,ME,RN,Oeste Potiguar (RN),100.0,0.0,0.15,NaN,NaN,0.29,3.38,NaN,0.01,1.31,NaN,2022,Percentual,df_2022_valor_da_produção_____do_total__me.xlsx
2,ME,SP,Ribeirão Preto (SP),100.0,0.0,0.00,NaN,10.93,62.42,0.41,NaN,6.23,2.93,8.70,2022,Percentual,df_2022_valor_da_produção_____do_total__me.xlsx
3,ME,PR,Noroeste Paranaense (PR),100.0,0.0,2.12,NaN,0.43,30.61,0.01,0.01,6.63,17.64,14.69,2022,Percentual,df_2022_valor_da_produção_____do_total__me.xlsx
4,ME,MS,Sudoeste de Mato Grosso do Sul (MS),100.0,0.0,0.21,NaN,0.00,13.46,0.19,NaN,0.00,40.80,42.30,2022,Percentual,df_2022_valor_da_produção_____do_total__me.xlsx

In [ ]:
# Adiciona a coluna tipo manualmente só para segurança
fato_abs['Tipo'] = 'Absoluto'
fato_pct['Tipo'] = 'Percentual'

# Unifica as duas tabelas em fato_agricultura
fato_agricultura = pd.concat([fato_abs, fato_pct], ignore_index=True)

# Visualiza as colunas e primeiras linhas
print(fato_agricultura.columns.tolist())
display(fato_agricultura.head())

['Nível', 'Código UF', 'Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica', 'Total', 'Algodão herbáceo (em caroço)', 'Arroz (em casca)', 'Cacau (em amêndoa)', 'Café (em grão) Total', 'Cana-de-açúcar', 'Feijão (em grão)', 'Fumo (em folha)', 'Laranja', 'Milho (em grão)', 'Soja (em grão)', 'Ano', 'Tipo de Dado', 'Arquivo Origem', 'Tipo']

,Nível,Código UF,"Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica",Total,Algodão herbáceo (em caroço),Arroz (em casca),Cacau (em amêndoa),Café (em grão) Total,Cana-de-açúcar,Feijão (em grão),Fumo (em folha),Laranja,Milho (em grão),Soja (em grão),Ano,Tipo de Dado,Arquivo Origem,Tipo
0,MU,SP,Igaratá (SP),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Absoluto
1,MU,SP,Igaratá (SP),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_plantada_hectares_mu.xlsx,Absoluto
2,MI,SP,Osasco (SP),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mi.xlsx,Absoluto
3,MI,SP,Santos (SP),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mi.xlsx,Absoluto
4,MU,MG,Contagem (MG),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Absoluto

In [ ]:
# Lista de colunas que são produtos (exclui id_vars)
id_vars = ['Nível', 'Código UF', 'Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica',
           'Ano', 'Tipo', 'Tipo de Dado', 'Arquivo Origem']

value_vars = [col for col in fato_agricultura.columns if col not in id_vars and col != 'Total']

# Derrete as colunas wide em long
fato_agricultura_long = pd.melt(fato_agricultura,
                                 id_vars=id_vars,
                                 value_vars=value_vars,
                                 var_name='Produto',
                                 value_name='Valor')

# Remove valores nulos
fato_agricultura_long = fato_agricultura_long.dropna(subset=['Valor'])

# Visualiza
display(fato_agricultura_long.head())

,Nível,Código UF,"Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica",Ano,Tipo,Tipo de Dado,Arquivo Origem,Produto,Valor
350,MU,PB,Brejo dos Santos (PB),2022,Absoluto,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Algodão herbáceo (em caroço),2.0
351,MU,PB,Brejo dos Santos (PB),2022,Absoluto,Absoluto,df_2022_área_plantada_hectares_mu.xlsx,Algodão herbáceo (em caroço),2.0
361,MU,PB,Coxixola (PB),2022,Absoluto,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Algodão herbáceo (em caroço),2.0
392,MU,RN,Carnaúba dos Dantas (RN),2022,Absoluto,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Algodão herbáceo (em caroço),5.0
411,MU,RN,Caicó (RN),2022,Absoluto,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Algodão herbáceo (em caroço),8.0

# 🔁 Merge e Enriquecimento dos Dados

In [ ]:
def extrair_variavel_unidade(nome_arquivo):
    nome = nome_arquivo.lower()

    if 'colhida' in nome:
        return 'Área colhida', 'hectares'
    elif 'plantada' in nome:
        return 'Área plantada', 'hectares'
    elif 'valor_da_produção' in nome:
        return 'Valor da produção', 'mil reais'
    elif 'rendimento' in nome:
        return 'Rendimento médio', 'kg/hectare'
    elif 'participação' in nome or 'do_total' in nome:
        return 'Participação percentual', '%'
    else:
        return 'Desconhecido', 'Desconhecido'

# Aplica função
fato_agricultura_long[['Variável', 'Unidade']] = fato_agricultura_long['Arquivo Origem'].apply(
    lambda x: pd.Series(extrair_variavel_unidade(x))
)

# Visualiza
display(fato_agricultura_long[['Arquivo Origem', 'Variável', 'Unidade']].drop_duplicates())

,Arquivo Origem,Variável,Unidade
350,df_2022_área_colhida_hectares_mu.xlsx,Área colhida,hectares
351,df_2022_área_plantada_hectares_mu.xlsx,Área plantada,hectares
597,df_2022_valor_da_produção_mil_reais_mu.xlsx,Valor da produção,mil reais
3473,df_2022_área_colhida_hectares_mi.xlsx,Área colhida,hectares
3737,df_2022_área_plantada_hectares_mi.xlsx,Área plantada,hectares
...,...,...,...
100849,df_2022_área_colhida___percentual_total_gr.xlsx,Área colhida,hectares
100852,df_2022_área_percentual_do_total_geral_gr.xlsx,Participação percentual,%
100927,df_2023_valor_da_produção_____do_total__gr.xlsx,Valor da produção,mil reais
100954,df_2023_área_colhida___percentual_total_gr.xlsx,Área colhida,hectares
100981,df_2023_área_percentual_do_total_geral_gr.xlsx,Participação percentual,%

In [ ]:
dim_produto = pd.DataFrame(fato_agricultura_long['Produto'].dropna().unique(), columns=['Nome_Produto'])
dim_produto['ID_Produto'] = dim_produto.index + 1
dim_produto = dim_produto[['ID_Produto', 'Nome_Produto']]

In [ ]:
dim_variavel = fato_agricultura_long[['Variável', 'Unidade']].drop_duplicates().reset_index(drop=True)
dim_variavel['ID_Variavel'] = dim_variavel.index + 1
dim_variavel = dim_variavel[['ID_Variavel', 'Variável', 'Unidade']]

In [ ]:
dim_ano = pd.DataFrame(fato_agricultura_long['Ano'].dropna().unique(), columns=['Ano'])
dim_ano['ID_Ano'] = dim_ano.index + 1
dim_ano = dim_ano[['ID_Ano', 'Ano']]

In [ ]:
desc_nivel = {
    'MU': 'Município',
    'MI': 'Microrregião',
    'ME': 'Mesorregião',
    'UF': 'Unidade da Federação',
    'GR': 'Grande Região'
}

dim_nivel = pd.DataFrame(fato_agricultura_long['Nível'].dropna().unique(), columns=['Nível'])
dim_nivel['Descrição'] = dim_nivel['Nível'].map(desc_nivel)
dim_nivel = dim_nivel[['Nível', 'Descrição']]

In [ ]:
dim_produto

   ID_Produto                  Nome_Produto
0           1  Algodão herbáceo (em caroço)
1           2              Arroz (em casca)
2           3            Cacau (em amêndoa)
3           4          Café (em grão) Total
4           5                Cana-de-açúcar
5           6              Feijão (em grão)
6           7               Fumo (em folha)
7           8                       Laranja
8           9               Milho (em grão)
9          10                Soja (em grão)

In [ ]:
dim_variavel

   ID_Variavel                 Variável       Unidade
0            1             Área colhida      hectares
1            2            Área plantada      hectares
2            3        Valor da produção     mil reais
3            4             Desconhecido  Desconhecido
4            5         Rendimento médio    kg/hectare
5            6  Participação percentual             %

In [ ]:
dim_ano

   ID_Ano   Ano
0       1  2022
1       2  2023

In [ ]:
dim_nivel

  Nível             Descrição
0    MU             Município
1    MI          Microrregião
2    ME           Mesorregião
3    UF  Unidade da Federação
4    GR         Grande Região

In [ ]:


import pandas as pd
# Caminho no seu Google Drive
caminho_dtb = '/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/IDs/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.ods'

# Carregando a aba correta (geralmente a primeira contém os dados)
dtb = pd.read_excel(caminho_dtb, engine='odf', skiprows=6)

# Exibindo as primeiras linhas
dtb.head()

Requirement already satisfied: odfpy in /usr/local/lib/python3.11/dist-packages (1.4.1)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.11/dist-packages (from odfpy) (0.7.1)

,UF,Nome_UF,Região Geográfica Intermediária( Mesorregião),Nome Região Geográfica Intermediária,Região Geográfica Imediata (Microrregião),Nome Região Geográfica Imediata,Município,Código Município Completo,Nome_Município,Unnamed: 9
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,NaN
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,379,1100379,Alto Alegre dos Parecis,NaN
2,11,Rondônia,1101,Porto Velho,110002,Ariquemes,403,1100403,Alto Paraíso,NaN
3,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,346,1100346,Alvorada D'Oeste,NaN
4,11,Rondônia,1101,Porto Velho,110002,Ariquemes,23,1100023,Ariquemes,NaN

# 🧱 Criação do Star Schema

In [ ]:
dim_uf.columns = [col.strip().lower().replace(' ', '_') for col in dim_uf.columns]
print(dim_uf.columns.tolist())

['uf']

In [ ]:
# Padronizar os tipos das chaves para merge
dtb['Código_UF'] = dtb['Código_UF'].astype(str)
dim_uf['Código_UF'] = dim_uf['Código_UF'].astype(str)

# Agora sim, realizar o merge
dim_territorio = dtb.merge(dim_uf, on='Código_UF', how='left')

# Visualizar resultado
dim_territorio.head()

,Código_UF,Nome_UF,Código_Mesorregiao,Nome_Mesorregiao,Código_Microrregiao,Nome_Microrregiao,Código_Municipio_7d,Código_Municipio,Nome_Municipio
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,379,1100379,Alto Alegre dos Parecis
2,11,Rondônia,1101,Porto Velho,110002,Ariquemes,403,1100403,Alto Paraíso
3,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,346,1100346,Alvorada D'Oeste
4,11,Rondônia,1101,Porto Velho,110002,Ariquemes,23,1100023,Ariquemes

In [ ]:
dim_territorio = dim_territorio[[
    'Código_UF', 'Nome_UF',
    'Código_Municipio', 'Nome_Municipio',
    'Código_Microrregiao', 'Nome_Microrregiao',
    'Código_Mesorregiao', 'Nome_Mesorregiao'
]].drop_duplicates()

# Renomear para manter padrão de nomes
dim_territorio.columns = [
    'Codigo_UF', 'Nome_UF',
    'Codigo_Municipio', 'Nome_Municipio',
    'Codigo_Microrregiao', 'Nome_Microrregiao',
    'Codigo_Mesorregiao', 'Nome_Mesorregiao'
]

# Validar resultado
dim_territorio.head()

,Codigo_UF,Nome_UF,Codigo_Municipio,Nome_Municipio,Codigo_Microrregiao,Nome_Microrregiao,Codigo_Mesorregiao,Nome_Mesorregiao
0,11,Rondônia,1100015,Alta Floresta D'Oeste,110005,Cacoal,1102,Ji-Paraná
1,11,Rondônia,1100379,Alto Alegre dos Parecis,110005,Cacoal,1102,Ji-Paraná
2,11,Rondônia,1100403,Alto Paraíso,110002,Ariquemes,1101,Porto Velho
3,11,Rondônia,1100346,Alvorada D'Oeste,110004,Ji-Paraná,1102,Ji-Paraná
4,11,Rondônia,1100023,Ariquemes,110002,Ariquemes,1101,Porto Velho

In [ ]:
# Extrair pares únicos de UF e Grande Região diretamente de dim_territorio
dim_grande_regiao = dim_territorio[['Codigo_UF', 'Nome_UF']].drop_duplicates().copy()

# Adicionar manualmente a grande região com base na UF
# Mapeamento IBGE oficial por código UF
mapa_grande_regiao = {
    12: 'Norte', 16: 'Norte', 13: 'Norte', 11: 'Norte', 14: 'Norte', 15: 'Norte', 17: 'Norte',
    21: 'Nordeste', 22: 'Nordeste', 23: 'Nordeste', 24: 'Nordeste', 25: 'Nordeste', 26: 'Nordeste', 27: 'Nordeste',
    29: 'Nordeste', 28: 'Nordeste',
    31: 'Sudeste', 32: 'Sudeste', 33: 'Sudeste', 35: 'Sudeste',
    41: 'Sul', 42: 'Sul', 43: 'Sul',
    50: 'Centro-Oeste', 51: 'Centro-Oeste', 52: 'Centro-Oeste', 53: 'Centro-Oeste'
}

dim_grande_regiao['Nome_Grande_Regiao'] = dim_grande_regiao['Codigo_UF'].map(mapa_grande_regiao)

# Criar um ID fictício para a Grande Região
dim_grande_regiao['Codigo_Grande_Regiao'] = dim_grande_regiao['Nome_Grande_Regiao'].astype('category').cat.codes + 1

# Reordenar colunas
dim_grande_regiao = dim_grande_regiao[['Codigo_Grande_Regiao', 'Nome_Grande_Regiao', 'Codigo_UF', 'Nome_UF']].drop_duplicates()

# Visualizar
dim_grande_regiao.head()

     Codigo_Grande_Regiao Nome_Grande_Regiao Codigo_UF   Nome_UF
0                       0                NaN        11  Rondônia
52                      0                NaN        12      Acre
74                      0                NaN        13  Amazonas
136                     0                NaN        14   Roraima
151                     0                NaN        15      Pará

In [ ]:
output_path = "/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Refatoradas/Star Schema"
dim_grande_regiao.to_excel("/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Refatoradas/Star Schema/dim_grande_regiao_corrigido.xlsx", index=False)
dim_grande_regiao.to_excel(f"{output_path}/dim_grande_regiao_corrigido.xlsx", index=False)

In [ ]:
dim_produto.to_excel(f"{output_path}/dim_produto.xlsx", index=False)
dim_variavel.to_excel(f"{output_path}/dim_variavel.xlsx", index=False)
dim_ano.to_excel(f"{output_path}/dim_ano.xlsx", index=False)
dim_nivel.to_excel(f"{output_path}/dim_nivel.xlsx", index=False)
dim_territorio.to_excel(f"{output_path}/dim_territorio.xlsx", index=False)

In [ ]:
fato_agricultura.to_excel(f"{output_path}/fato_agricultura_reconstruida.xlsx", index=False)

In [ ]:
# Leitura dos arquivos exportados
dim_produto = pd.read_excel(os.path.join(output_path, "dim_produto.xlsx"))
dim_variavel = pd.read_excel(os.path.join(output_path, "dim_variavel.xlsx"))
dim_ano = pd.read_excel(os.path.join(output_path, "dim_ano.xlsx"))
dim_nivel = pd.read_excel(os.path.join(output_path, "dim_nivel.xlsx"))
dim_territorio = pd.read_excel(os.path.join(output_path, "dim_territorio.xlsx"))
fato_agricultura = pd.read_excel(os.path.join(output_path, "fato_agricultura_reconstruida.xlsx"))

In [ ]:
# Exibir as primeiras 5 linhas de cada tabela para validação
{
    "dim_produto": dim_produto.head(),
    "dim_variavel": dim_variavel.head(),
    "dim_ano": dim_ano.head(),
    "dim_nivel": dim_nivel.head(),
    "dim_territorio": dim_territorio.head(),
    "fato_agricultura": fato_agricultura.head()
}

In [ ]:
## Passo 1 – Adicionar ID_Variavel na fato_agricultura
#Vamos associar cada linha da tabela fato à sua variável (e respectiva unidade) com base na coluna 'Arquivo Origem'. O mapeamento já está contido na `dim_variavel`.

# 🧪 Validação Final e Exportação

In [ ]:
# Caminho de saída usado
output_path = "/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Refatoradas/Star Schema"

# Carregando fato_agricultura
fato_agricultura = pd.read_excel(os.path.join(output_path, "fato_agricultura_reconstruida.xlsx"))

# Visualizar as primeiras linhas
fato_agricultura.head()

,Nível,Código UF,"Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica",Total,Algodão herbáceo (em caroço),Arroz (em casca),Cacau (em amêndoa),Café (em grão) Total,Cana-de-açúcar,Feijão (em grão),Fumo (em folha),Laranja,Milho (em grão),Soja (em grão),Ano,Tipo de Dado,Arquivo Origem,Tipo
0,MU,SP,Igaratá (SP),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Absoluto
1,MU,SP,Igaratá (SP),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_plantada_hectares_mu.xlsx,Absoluto
2,MI,SP,Osasco (SP),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mi.xlsx,Absoluto
3,MI,SP,Santos (SP),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mi.xlsx,Absoluto
4,MU,MG,Contagem (MG),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Absoluto

In [ ]:
# Carregar a tabela dim_variavel
dim_variavel = pd.read_excel(os.path.join(output_path, "dim_variavel.xlsx"))

# Visualizar as primeiras linhas
dim_variavel.head()

   ID_Variavel           Variável       Unidade
0            1       Área colhida      hectares
1            2      Área plantada      hectares
2            3  Valor da produção     mil reais
3            4       Desconhecido  Desconhecido
4            5   Rendimento médio    kg/hectare

In [ ]:
# Verificar o nome das colunas disponíveis na tabela
print(dim_variavel.columns)

Index(['ID_Variavel', 'Variável', 'Unidade'], dtype='object')

In [ ]:
# Carregando a tabela de mapeamento entre Arquivo Origem e Variável
dim_medidas_sidra = pd.read_excel(
    "/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Refatoradas/dim_medidas_sidra.xlsx"
)

# Exibir colunas para confirmar estrutura
dim_medidas_sidra.columns

Index(['Medida', 'Tipo', 'Descrição'], dtype='object')

In [ ]:
# Visualizar amostra do conteúdo da coluna 'Descrição'
dim_medidas_sidra[['Descrição']].head(10)

                                         Descrição
0                   Área destinada à colheita (ha)
1                   Área efetivamente colhida (ha)
2  Produção total (em toneladas, 1 ton = 1 000 kg)
3                     Produtividade média em kg/ha
4                 Valor monetário da produção (R$)
5          Agregado ou total de todas as variáveis
6        Quantidade produzida de café em toneladas
7      Quantidade produzida de feijão em toneladas
8     Quantidade produzida de algodão em toneladas
9                    Produção de cana em toneladas

In [ ]:
fato_agricultura.columns.tolist()

['Nível',
 'Código UF',
 'Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica',
 'Total',
 'Algodão herbáceo (em caroço)',
 'Arroz (em casca)',
 'Cacau (em amêndoa)',
 'Café (em grão) Total',
 'Cana-de-açúcar',
 'Feijão (em grão)',
 'Fumo (em folha)',
 'Laranja',
 'Milho (em grão)',
 'Soja (em grão)',
 'Ano',
 'Tipo de Dado',
 'Arquivo Origem',
 'Tipo']

In [ ]:
# Gerar lista única de arquivos de origem para mapeamento manual
arquivos_origem_unicos = fato_agricultura[['Arquivo Origem']].drop_duplicates().reset_index(drop=True)

# Exportar para preenchimento manual
path_saida_mapeamento = os.path.join(output_path, "dim_variavel_com_arquivo.xlsx")
arquivos_origem_unicos.to_excel(path_saida_mapeamento, index=False)

print("Arquivo salvo para preenchimento em:", path_saida_mapeamento)

Arquivo salvo para preenchimento em: /content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Refatoradas/Star Schema/dim_variavel_com_arquivo.xlsx

In [ ]:
# Caminho do arquivo preenchido manualmente no Google Drive
path_dim_variavel_arquivo = os.path.join(output_path, "dim_variavel_com_arquivo.xlsx")

# Carregar o arquivo com o mapeamento manual
dim_variavel_arquivo = pd.read_excel(path_dim_variavel_arquivo)

# Confirmar as primeiras linhas
dim_variavel_arquivo.head()

                                Arquivo Origem
0        df_2022_área_colhida_hectares_mu.xlsx
1       df_2022_área_plantada_hectares_mu.xlsx
2        df_2022_área_colhida_hectares_mi.xlsx
3       df_2022_área_plantada_hectares_mi.xlsx
4  df_2022_valor_da_produção_mil_reais_mi.xlsx

In [ ]:
# Caminho de saída usado
output_path = "/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Refatoradas/Star Schema"

# Caminho do arquivo preenchido manualmente no Google Drive
path_dim_variavel_arquivo = os.path.join(output_path, "dim_variavel_com_arquivo.xlsx")

# Carregar o arquivo com o mapeamento manual
# **Verifique se este arquivo 'dim_variavel_com_arquivo.xlsx' foi editado manualmente**
# **para incluir as colunas 'Variável' e 'Unidade' com os mapeamentos corretos.**
try:
    dim_variavel_arquivo = pd.read_excel(path_dim_variavel_arquivo)
    # Confirme que as colunas esperadas existem
    if 'Variável' not in dim_variavel_arquivo.columns or 'Unidade' not in dim_variavel_arquivo.columns:
        print("Erro: O arquivo 'dim_variavel_com_arquivo.xlsx' não contém as colunas 'Variável' e 'Unidade'.")
        print("Por favor, edite este arquivo manualmente no Google Drive e adicione essas colunas com os mapeamentos.")
        # Adicione as colunas vazias para que o código possa continuar, mas alertando o usuário
        if 'Variável' not in dim_variavel_arquivo.columns:
             dim_variavel_arquivo['Variável'] = None
        if 'Unidade' not in dim_variavel_arquivo.columns:
             dim_variavel_arquivo['Unidade'] = None
except FileNotFoundError:
    print(f"Erro: Arquivo não encontrado no caminho: {path_dim_variavel_arquivo}")
    # Criar um DataFrame vazio ou com estrutura mínima para evitar quebra
    dim_variavel_arquivo = pd.DataFrame(columns=['Arquivo Origem', 'Variável', 'Unidade'])
    print("Por favor, verifique o caminho do arquivo.")


# Carregar a tabela dim_variavel (gerada anteriormente no notebook)
dim_variavel = pd.read_excel(os.path.join(output_path, "dim_variavel.xlsx"))

# Fazer merge do mapeamento manual com a dimensão de variável para obter o ID
# Este merge agora deve funcionar SE 'dim_variavel_arquivo' tiver as colunas 'Variável' e 'Unidade'
dim_variavel_arquivo = dim_variavel_arquivo.merge(
    dim_variavel[['ID_Variavel', 'Variável', 'Unidade']], # Seleciona apenas as colunas necessárias da dim_variavel
    on=['Variável', 'Unidade'],
    how='left'
)

# Carregando fato_agricultura novamente para garantir que está atualizada se necessário
fato_agricultura = pd.read_excel(os.path.join(output_path, "fato_agricultura_reconstruida.xlsx"))


# Fazer merge final com a fato_agricultura, adicionando ID_Variavel
# Usar as colunas do DataFrame após o primeiro merge
fato_agricultura = fato_agricultura.merge(
    dim_variavel_arquivo[['Arquivo Origem', 'ID_Variavel']],
    on='Arquivo Origem',
    how='left'
)

# Verificar se foi inserido corretamente
print("\nMapeamento de Arquivo Origem para ID_Variavel:")
display(fato_agricultura[['Arquivo Origem', 'ID_Variavel']].drop_duplicates().head())

print("\nPrimeiras linhas da fato_agricultura com ID_Variavel:")
display(fato_agricultura.head())

# Opcional: Salvar a fato_agricultura atualizada
# fato_agricultura.to_excel(os.path.join(output_path, "fato_agricultura_com_ids.xlsx"), index=False)

Erro: O arquivo 'dim_variavel_com_arquivo.xlsx' não contém as colunas 'Variável' e 'Unidade'.
Por favor, edite este arquivo manualmente no Google Drive e adicione essas colunas com os mapeamentos.

Mapeamento de Arquivo Origem para ID_Variavel:

                                 Arquivo Origem  ID_Variavel
0         df_2022_área_colhida_hectares_mu.xlsx          NaN
1        df_2022_área_plantada_hectares_mu.xlsx          NaN
2         df_2022_área_colhida_hectares_mi.xlsx          NaN
8        df_2022_área_plantada_hectares_mi.xlsx          NaN
14  df_2022_valor_da_produção_mil_reais_mi.xlsx          NaN

Primeiras linhas da fato_agricultura com ID_Variavel:

,Nível,Código UF,"Grande Região, Unidade da Federação, Município, Mesorregião Geográfica e Microrregião Geográfica",Total,Algodão herbáceo (em caroço),Arroz (em casca),Cacau (em amêndoa),Café (em grão) Total,Cana-de-açúcar,Feijão (em grão),Fumo (em folha),Laranja,Milho (em grão),Soja (em grão),Ano,Tipo de Dado,Arquivo Origem,Tipo,ID_Variavel
0,MU,SP,Igaratá (SP),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Absoluto,NaN
1,MU,SP,Igaratá (SP),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_plantada_hectares_mu.xlsx,Absoluto,NaN
2,MI,SP,Osasco (SP),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mi.xlsx,Absoluto,NaN
3,MI,SP,Santos (SP),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mi.xlsx,Absoluto,NaN
4,MU,MG,Contagem (MG),2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2022,Absoluto,df_2022_área_colhida_hectares_mu.xlsx,Absoluto,NaN

In [ ]:
# Caminho do output
output_path = "/content/drive/MyDrive/DNC/Projetos/Becomex/01. Base de dados/SIDRA/TRATADOS/Fato & Dimensao/Refatoradas/Star Schema"

# 1. Carregar a dimensão território e a fato novamente
dim_territorio = pd.read_excel(os.path.join(output_path, "dim_territorio.xlsx"))
fato_agricultura = pd.read_excel(os.path.join(output_path, "fato_agricultura_reconstruida.xlsx"))

# 2. Verificar tipos das colunas de ligação
print("Tipo Código UF na fato:", fato_agricultura['Código UF'].dtype)
print("Tipo Código UF na dimensão:", dim_territorio['Codigo_UF'].dtype)

# 3. Padronizar tipos para garantir merge correto
# Use pd.to_numeric with errors='coerce' to handle non-numeric values
fato_agricultura['Codigo_UF'] = pd.to_numeric(fato_agricultura['Código UF'], errors='coerce')

# Drop rows where the conversion failed (where Codigo_UF is NaN) as they cannot be merged
fato_agricultura.dropna(subset=['Codigo_UF'], inplace=True)

# Now convert to integer type (can be Int64 to handle potential NaNs introduced by coerce)
fato_agricultura['Codigo_UF'] = fato_agricultura['Codigo_UF'].astype('Int64') # Use nullable integer type

# Convert dim_territorio's Codigo_UF to Int64 as well for consistency
dim_territorio['Codigo_UF'] = dim_territorio['Codigo_UF'].astype('Int64')


# 4. Merge para checagem (apenas algumas colunas para não poluir)
# Note: If you used Int64, the merge will work correctly with potential NaNs in fato_agricultura
df_check_merge = fato_agricultura.merge(
    dim_territorio[['Codigo_UF', 'Nome_UF']], on='Codigo_UF', how='left'
)

# 5. (Opcional) Adicionar UF sigla na fato_agricultura
# This merge will also work correctly with Int64 types
fato_agricultura = fato_agricultura.merge(
    dim_territorio[['Codigo_UF', 'Nome_UF']], on='Codigo_UF', how='left'
)

# Renomear se quiser manter ambos:
# fato_agricultura.rename(columns={'Nome_UF': 'UF_Sigla'}, inplace=True)

# 6. Verificar resultado
print("\nUFs adicionadas:")
display(fato_agricultura[['Codigo_UF', 'Nome_UF']].drop_duplicates().head())

# 7. Salvar versão atualizada com sigla de UF
fato_agricultura.to_excel(os.path.join(output_path, "fato_agricultura_reconstruida.xlsx"), index=False)

Tipo Código UF na fato: object
Tipo Código UF na dimensão: int64

UFs adicionadas:

Empty DataFrame
Columns: [Codigo_UF, Nome_UF]
Index: []